### ISSUE TITLE
One-to-One and One-to-Many Relationships

### ISSUE THREAD

**Issue by ixnp** [learn-co-curriculum/python-p3-intro-to-sqlalchemy-relationships#1]
### Canvas Link

https://learning.flatironschool.com/courses/6049/assignments/204249?module_item_id=468035

### Concern

The One-to-One and One-to-Many Relationships assignment links to this repo instead of the One-to-One and One-to-Many Relationships repo.

**Comment by professor-ben** [comment]
re-initialized the repo. unclear what happened here. thanks for the heads up.
