### ISSUE TITLE
pipfile.lock

### ISSUE THREAD

**Issue by ixnp** [learn-co-curriculum/python-p3-intro-to-sqlalchemy-relationships#2]
### Canvas Link

https://learning.flatironschool.com/courses/6049/assignments/204246?module_item_id=468036

### Concern

Debugging: Had to delete the pipfile.lock and re-install to run any of the commands

**Comment by professor-ben** [comment]
updated Pipfile.lock to reflect need for 3.8.13, eliminate dev dependencies
